export const productData = [
  {
    id: 1,
    title: 'Egg & Vegetable Dish',
    description: 'untitled',
    price: 12.60,
    rating: 4.69,
    stock: 94,
    quantity: 2,
    brand: 'untitled',
    category: 'Egg & Veg',
    thumbnail: 'https://i.ibb.co/6snSB6m/Egg-Veg.jpg'
  },
  {
    id: 2,
    title: 'Shrimp Pasta',
    description: 'untitled',
    price: 26.50,
    rating: 4.44,
    stock: 34,
    quantity: 3,
    brand: 'untitled',
    category: 'Pasta',
    thumbnail: 'https://i.ibb.co/7K4c242/pasta.jpg'
  },
  {
    id: 3,
    title: 'Cooked Reindeer Meat',
    description: 'untitled',
    price: 33.50,
    rating: 4.09,
    stock: 36,
    quantity: 2,
    brand: 'untitled',
    category: 'Meat',
    thumbnail: 'https://i.ibb.co/QNfqQp8/reindeer.jpg'
  },
  {
    id: 4,
    title: 'Shrimp Dish',
    description: 'untitled',
    price: 28.80,
    rating: 4.3,
    stock: 123,
    quantity: 1,
    brand: 'untitled',
    category: 'Fish',
    thumbnail: 'https://i.ibb.co/dDgNHKx/shrimp.jpg'
  },
  {
    id: 5,
    title: 'Feta Salad',
    description: 'untitled',
    price: 12.50,
    rating: 4.09,
    stock: 32,
    quantity: 6,
    brand: 'untitled',
    category: 'Salads',
    thumbnail: 'https://i.ibb.co/j42Xmdq/Feta-Salad.jpg" '
  },
  {
    id: 6,
    title: 'Sashimi Salmon',
    description: 'untitled',
    price: 23.50,
    rating: 4.57,
    stock: 83,
    quantity: 7,
    brand: 'untitled',
    category: 'Fish',
    thumbnail: 'https://i.ibb.co/z4kkwmP/sashimi.jpg'
  },
  {
    id: 7,
    title: 'Beef Steak',
    description: 'untitled',
    price: 32.50,
    rating: 4.25,
    stock: 50,
    quantity: 5,
    brand: 'untitled',
    category: 'Meat',
    thumbnail: 'https://i.ibb.co/ZYY2vmx/beef.jpg'
  },
  {
    id: 8,
    title: 'untitled',
    description: 'Meal with Salmon and Zucchini',
    price: 36.50,
    rating: 4.43,
    stock: 68,
    quantity: 3,
    brand: 'untitled',
    category: 'fish',
    thumbnail: 'https://i.ibb.co/f82QBrF/salmon.jpg'
  },
  {
    id: 9,
    title: 'Burger',
    description: 'untitled',
    price: 19.50,
    rating: 4.54,
    stock: 96,
    quantity: 2,
    brand: 'untitled',
    category: 'untitled',
    thumbnail: 'https://i.ibb.co/n0XVK6V/burger.jpg'
  },
  {
    id: 10,
    title: 'Lamb Ribs',
    description: 'untitled',
    price: 25,
    rating: 4.43,
    stock: 32,
    quantity: 4,
    brand: 'untitled',
    category: 'untitled',
    thumbnail: 'https://i.ibb.co/2kG2vBM/lamb.jpg',

  }
]